### ISSUE TITLE
Capturing mouse clicks

### ISSUE THREAD

**Issue by lukasstevens** [antoyo/webkit2gtk-rs#2]
Hello, I have the following problem and thought that you can maybe help me:
I am currently developing a drop-in replacement for i3bar. The important difference is that my application is able to display html. It achieves this by utilizing webkit2gtk-rs. So far this does work pretty good and my application is nearly finished with one important feature missing: click events. 

First some information about the application. Via the standard input it receives and parses messages encoded with the i3bar protocol. This protocol basically specifies a list of blocks and information about the respective blocks, most importantly what the text(or html) for that block is. My application then displays the blocks in the order of the list. 
Now I want to also be able to determine when a mouse click happens and additionally which block was clicked. I am thinking that it is probably possible to insert some javascript code for the blocks and then use callbacks to achieve this.

Do you have any ideas?

**Comment by antoyo** [comment]
The simplest way is probably to use [`run_javascript_with_callback`](https://github.com/antoyo/webkit2gtk-rs/blob/master/src/web_view.rs#L59).
Another way would be to create a webkit web extension and communicate between the two projects (for instance, via DBUS).
You can find an example of doing so in [titanium](https://github.com/antoyo/titanium/tree/master/titanium-web-extension).

**Comment by lukasstevens** [comment]
I had a look into this and I am not quite sure how to properly implement this. When using `run_javascript_with_callback` the javascript code has to block until a mouse event happens. I would then get the mouse event and would have to rerun the javascript code. This would work, but is probably relatively resource intensive. 

If I would go the route of using a webextension then I have the problem that I don't know when a mouse event happens. One thing I could do is to inject javascript which handles mouse events and encodes the mouse event as an URI request. In my webextension I can now register a callback with `connect_send_request` which extracts the mouse event somehow, sends it to my GUI process and finally resets the URI. This solution is a bit hacky though.

**Comment by antoyo** [comment]
Look at the [documentation for WebKitDOMGTK+](https://webkitgtk.org/reference/webkitdomgtk/stable/index.html) which allows you to call the same method as in JavaScript from a web extension.
You probably need the [`add_event_listener` method](https://webkitgtk.org/reference/webkitdomgtk/stable/webkitdomgtk-4.0-WebKitDOMEventTarget.html#webkit-dom-event-target-add-event-listener).
Unfortunately, it is [not generated](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/src/auto/dom_event_target.rs#L20) by now.

I will take a look in a few weeks since I'm really busy.

If you want to contribute, I'll help you to understand how this code is generated.
Nevertheless, callbacks are a bit tricky to auto-generate right now.
Perhaps we'll need to implement this function manually, as I did for [`run_javascript_with_callback`](https://github.com/antoyo/webkit2gtk-rs/blob/master/src/web_view.rs#L89).

**Comment by lukasstevens** [comment]
Having this function would be awesome (for me). If you are busy right now I am glad to wait, since this only a pet project of mine. I would like to contribute, but as you said I would need to understand how the generation works first. Additionally if the method has to implemented manually I don't know if I am able to correctly implement it with my knowledge.

**Comment by lukasstevens** [comment]
Hey, what is the status of this issue?

**Comment by antoyo** [comment]
I did not have time to look at this issue yet: I'm busy with my `relm` and `mg` crates, these days.

**Comment by antoyo** [comment]
@lukasstevens: Just so you know, I didn't forget you :) .
I started to work on adding [a `Closure` type in glib](https://github.com/gtk-rs/glib/pull/173) which is needed for `add_event_listener`.
Hopefully, I will be able to add this method soon.

**Comment by lukasstevens** [comment]
Very nice. Thank you :)

**Comment by antoyo** [comment]
This issue is now fixed since `Closure` support was finally merge into the `glib` master branch.
You can try the example [here](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/example/src/lib.rs#L43-L47).
Please tell me if everything works fine for you.

**Comment by lukasstevens** [comment]
Awesome. I will try to have a look at it this weekend.

**Comment by lukasstevens** [comment]
Hello, I had a look at this today and I can now register a callback for click events. I have one problem, though. How do I get the `DOMMouseEvent` out of the `&[Values]` array?
When I use the following code I always receive `None` for some reason.
```rust
    extension.connect_page_created(|_, page| {
        let document = page.get_dom_document().unwrap();
        let handler = Closure::new(|value| {
            let mouse_event: Option<DOMMouseEvent> = value[1].get(); // This is always None
            debug!("{:?}", &mouse_event);;
            None
        });
        document.add_event_listener_with_closure("click", &handler, false);
    });
```

**Comment by antoyo** [comment]
I updated the [example](https://github.com/antoyo/webkit2gtk-webextension-rs/blob/master/example/src/lib.rs#L54-L58) to do what you want to do.

**Comment by lukasstevens** [comment]
Thank you, now it works.
